### ISSUE TITLE
Re-Create Medium-Style Blog Post UI/Layout in Tachyons

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tachyons#13]
Medium.com (_for better or worse_) has taken over the "_market_" for 
One thing they _definately_ got right is the Design/Page Layout.
![image](https://cloud.githubusercontent.com/assets/194400/25771446/93dc88ac-3249-11e7-860f-c3b2ccb59bc6.png)
https://uxplanet.org/metaphors-and-analogies-in-product-design-b9af77c18dba

## Task/Todo

+ [ ] create a `/examples/medium-style-blog-post.html` file
+ [ ] open a random post/article on Medium with your chrome developer tools
+ [ ] replicate it component-for-component

p.s: _most_ people recognise that Medium were _not_ the first to layout a page this way.
There were _many_ people doing the "Hero Image" + Good Information Hierarchy and Typography _long_ before Medium came along; I'm using "Medium-Style" a _reference_ we all _understand_.
also, I found`this` an _interesting_ read: https://thehustle.co/airbnb-medium-beats-flipboard-logo

**Comment by klazich** [comment]
Hey, @nelsonic,

I'm working on a course project and was thinking of using Medium's page layout and came across this while searching. When the project is finished I'll come back here if this is still open.

**Comment by iteles** [comment]
@klazich Hooray! You might also be interested in https://tachyons-bootstrap.dwyl.com/ (which is just a URL for https://github.com/dwyl/tachyons-bootstrap)

**Comment by klazich** [comment]
It's been about a month, I thought i would check in. I'm finishing up my project. It can be found [here](https://github.com/klazich/on-functional-css). And, the gh-page is [here](https://klazich.github.io/on-functional-css/). 

Is something like this what you were looking for? I got the permission of Adam Morse to use his awesome write-up, [Css and Scalability ](http://mrmrs.github.io/writing/2016/03/24/scalable-css/) as the content for the blog post. 

I'll start putting together a PR soon, hopefully. I'll take out the javascript.

**Comment by cwonrails** [comment]
@klazich This is awesome, thanks so much!
