### ISSUE TITLE
How to create an image placeholder?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tachyons#46]
In a project we are currently working on, people can upload images of content when one is available.
We want to display a "placeholder" image to signal to users that there is currently no image available,
and to _remind_ the content owner that there is a "gap" that needs to be filled. 

# Todo

+ [x] Create a basic image placeholder from scratch in a freely available drawing program
+ [x] Export the placeholder image as an image file (_e.g: `.jpg`, `.png` or `.gif`_)
+ [x] Upload the image to GitHub (_so we use Microsoft's infinite bandwidth on AWS S3/Cloudfront CDN_)
+ [x] Display the image on a page centred within a div 
+ [x] Display the pixel dimensions as a reminder to the content owner what the ideal dimensions for the image are.
+ [x] Document and _explain_ how it works to other people!

## Background / Context 

We have been using this image in our project: 
http://www.camera-m.com/img/placeholder-image-wide.png 
![image](https://user-images.githubusercontent.com/194400/49531010-48dad180-f8b1-11e8-8d89-1e61320e1d82.png)
The image is insecure. (_served over HTTP not HTTPS_) which prompted us opening _this_ issue.

## Research

A Google Image Search for "***image placeholder***" returns _many_ similar results:
https://www.google.com/search?tbm=isch&q=image+placeholder
![image](https://user-images.githubusercontent.com/194400/49568991-8cbded00-f92a-11e8-9cff-adc866e95379.png)
This type of generic image on a grey background appears to be the consensus for "image placeholder".

**Comment by nelsonic** [comment]
I made a slightly modified version of the placeholder image in dwaw.io in (_less than_) 2 minutes: 
https://drive.google.com/file/d/1gOdr5EXzodSFRNU_7BLCgckPrghUGkx4
![image](https://user-images.githubusercontent.com/194400/49568908-4ec0c900-f92a-11e8-9038-46deb6859325.png)

**Comment by nelsonic** [comment]
Exported form Draw.io the `.png` is **3KB**:
![image](https://user-images.githubusercontent.com/194400/49568391-cb52a800-f928-11e8-8ffc-9f6bab34336e.png)

The original used is **5KB**:
![image](https://user-images.githubusercontent.com/194400/49531128-88a1b900-f8b1-11e8-96b9-083bde46a9d2.png)

So in 5 minutes I've saved 40% bandwidth for the users

**Comment by nelsonic** [comment]
Draw.io export image:
![image](https://user-images.githubusercontent.com/194400/49571545-87b06c00-f931-11e8-86dc-67f257dd42d7.png)

![image-placehoder-124-114-px](https://user-images.githubusercontent.com/194400/49571717-f392d480-f931-11e8-96f2-a8d10cfe375e.png)

Wrap the image in a bit hot HTML + Tachyons:
```html
    <div class="center bg-light-gray ba b--gray tc"
      style="width: 800px; height: 300px;">
    <img class="center v-mid pt5"/
     alt="Placeholder Image - Please upload an appropriate one."
     src="https://user-images.githubusercontent.com/194400/49571717-f392d480-f931-11e8-96f2-a8d10cfe375e.png">
      <p class="v-btm fw1">This is a placeholder image. <br />
        Please upload a more relevant one. Ideal dimensions:<br />
        <b class="fw5 pt2">Width: 800 pixels, Height: 300 pixels.</b></p>
    </div>
```

![image](https://user-images.githubusercontent.com/194400/49573332-a57fd000-f935-11e8-9188-7f5a038a18b5.png)

A _versatile/customisable_ image placeholder we can drop into _any_ project.

Done.
